disable test commands, we have no tests

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -42,15 +42,18 @@ jobs:
           restore-keys: ${{ runner.os }}-composer-
       - name: Install Composer dependencies
         run: composer install --no-progress --prefer-dist --optimize-autoloader
-      - name: Run Migration
-        run: |
-          composer require --dev symfony/orm-pack
-          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
-        env:
-          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8
-      - name: Install PHPUnit
-        run: simple-phpunit install
-      - name: Run tests
-        run: simple-phpunit --coverage-text
 
+        # TODO: Add the installation and test commands here
+
+#      - name: Run Migration
+#        run: |
+#          composer require --dev symfony/orm-pack
+#          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+#          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+#        env:
+#          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8
+#      - name: Install PHPUnit
+#        run: simple-phpunit install
+#      - name: Run tests
+#        run: simple-phpunit --coverage-text
+#
